name: Alpha Seeker v4.3 Enhanced Final Analysis

on:
  schedule:
    - cron: '7 21 * * 0-4'    # 06:07 KST (일-목)
    - cron: '30 14 * * 0-4'   # 23:30 KST (일-목) - 개선된 시간
    - cron: '23 9 * * 0'      # 18:23 KST (일요일)
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 600  # 10시간 (실시간 모니터링 포함)
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Alpha Seeker Enhanced Final Analysis
      env:
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMERGENCY_CHAT_ID: ${{ secrets.EMERGENCY_CHAT_ID }}
      run: python main.py
      
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: alpha-seeker-logs
        path: |
          alpha_seeker.log
          data/
